config/routes.rb
MusicApp::Application.routes.draw do
  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end
  resources :tracks, except: [:index, :new] do
    resources :notes, only: :show
  end
  resources :notes, only: [:create, :destroy]
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id           :integer          not null, primary key
#  track_id     :integer          not null
#  user_id      :integer          not null
#  note_content :text             not null
#

class Note < ActiveRecord::Base

  validates :track_id, :user_id, :note_content, presence: true

  belongs_to(
    :author,
    :class_name => "User",
    :foreign_key => :user_id,
    :primary_key => :id
  )

  belongs_to(
    :track,
    :class_name => "Track",
    :foreign_key => :track_id,
    :primary_key => :id
  )

  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  before_action :require_current_user!

  def create
    parameters = {}
    notes_params.each do |key,value|
      parameters[key] = value
    end
    parameters[:user_id] = current_user.id
    @note = Note.new(parameters)
    @track = Track.find(@note.track_id)

    if @note.save
      redirect_to track_url(@track)
    else
      redirect_to track_url(@track)
    end
  end

  # def new
  #   @track = Track.new
  #   @album = Album.find(params[:album_id])
  #   @track.album_id = @album.id
  #   render :new
  # end

  # def edit
  #   @track = Track.find(params[:id])
  #   @album = Album.find(@track.album_id)
  #   render :edit
  # end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  # def update
  #   @track = Track.find(params[:id])
  #   if @track.update(track_params)
  #     redirect_to track_url(@track)
  #   else
  #     @album = Album.find(@track.album_id)
  #     render :edit
  #   end
  # end

  def destroy
    @note = Note.find(params[:id])
    unless @note.author == current_user
      return
    end
    @track = Track.find(@note.track_id)
    @note.destroy
    redirect_to track_url(@track)
  end


  private

  def notes_params
    params.require(:note).permit(:track_id, :note_content)
  end
end

app/views/notes/_new_note_form.html.erb
<form action="<%= notes_url %>" method="post">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <input type="hidden" name="note[track_id]" value="<%= track.id %>">
  <br>
  <label for="new_note">Add a Note</label>
  <br>
  <textarea id="new_note"
  name="note[note_content]" value="">
  </textarea>
  <br>
  <button>Add Note</button>
</form>

app/views/notes/_notes_form.html.erb
<% author = User.find(note.user_id) %>
<br>
<%= note.note_content %>
<br>
<%= "--#{author.username}" %>

<% if author == current_user %>
<form action="<%= note_url(note) %>" method="post">
  <input type="hidden" name="_method" value="delete">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <button>Delete This Note</button>
</form>
<% end %>
<br>