config/routes.rb
MusicApp::Application.routes.draw do
  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end
  resources :tracks, except: [:index, :new] do
    resources :notes, only: :show
  end
  resources :notes, only: [:create, :destroy]
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id          :integer          not null, primary key
#  track_title :string(255)      not null
#  album_id    :integer          not null
#  track_type  :string(255)      not null
#  lyrics      :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Track < ActiveRecord::Base

  validates :track_title, :album_id, :track_type, presence: true

  belongs_to(
    :album,
    :class_name => "Album",
    :foreign_key => :album_id,
    :primary_key => :id
  )

  has_many(
    :notes,
    :dependent => :destroy,
    :class_name => "Note",
    :foreign_key => :track_id,
    :primary_key => :id
  )
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :require_current_user!

  def create
    @track = Track.new(track_params)
    if @track.save
      redirect_to track_url(@track)
    else
      @album = Album.find(@track.album_id)
      render :new
    end
  end

  def new
    @track = Track.new
    @album = Album.find(params[:album_id])
    @track.album_id = @album.id
    render :new
  end

  def edit
    @track = Track.find(params[:id])
    @album = Album.find(@track.album_id)
    render :edit
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to track_url(@track)
    else
      @album = Album.find(@track.album_id)
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @album = Album.find(@track.album_id)
    @track.destroy
    redirect_to album_url(@album.id)
  end


  private

  def track_params
    params.require(:track).permit(:track_title, :album_id, :track_type, :lyrics)
  end
end

app/views/tracks/_track_form.html.erb
<% input_url = action == :new ? tracks_url : track_url(track) %>
<% input_method = action == :new ? "post" : "patch" %>
<% button_text = action == :new ? "Create Track" : "Submit Changes" %>
<% albums = Album.all %>

<form action="<%= input_url %>" method="post">
  <input type="hidden" name="_method" value="<%= input_method %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="track_title">Track Title</label>
  <input id="track_title"
         type="text"
         name="track[track_title]"
         value="<%= track.track_title %>">

  <br>
  <label for="album_name">Album</label>
  <select id="album_name" name="track[album_id]">
    <% albums.each do |album| %>
      <option value="<%= album.id %>"
        <%= "selected" if album.id == track.album_id %> >
        <%= album.album_title %>
      </option>
    <% end %>
  </select>
  <br><br>
  Track Type
  <br>

  <label for="track_type_regular">Regular</label>
  <input id="track_type_regular" type="radio"
         name="track[track_type]" value="regular"
        <%= "checked" if track.track_type == "regular" %>  >

  <label for="track_type_bonus">Bonus</label>
  <input id="track_type_bonus" type="radio"
         name="track[track_type]" value="bonus"
        <%= "checked" if track.track_type == "bonus" %>  >
  <br>

  <label for="track_lyrics">Lyrics</label>
  <textarea id="track_lyrics"
  name="track[lyrics]" value="<%= track.lyrics %>"
  ><%= track.lyrics %></textarea>

  <br>
  <button><%= button_text %></button>
</form>
<br>
<a href="<%= album_url(album) %>"><button><%= album.album_title %></button></a>

app/views/tracks/edit.html.erb
<h1>Edit Track</h1>

<%= render "track_form",
    album: @album,
    track: @track,
    action: :edit %>

app/views/tracks/new.html.erb
<h1>Create Track</h1>
<%= render "track_form", album: @album, track: @track, action: :new %>

app/views/tracks/show.html.erb
<% album = Album.find(@track.album_id) %>

<h1><%= @track.track_title.capitalize %></h1>
<br>
Type: <%= @track.track_type.capitalize %>
<br>
<%= @track.lyrics %>
<br>


<a href="<%= edit_track_url(@track) %>"><button>Edit Track</button></a>
<br><br>

<form action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="delete">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <button>Delete This Track</button>
</form>
<br>
<a href="<%= album_url(album) %>">
  <button>
    All <%= album.album_title %> Tracks
  </button>
</a>
<br>
<% notes = @track.notes %>
<% notes.each do |note| %>
  <%= render "notes/notes_form", note: note %>
<% end %>


<%= render "notes/new_note_form", track: @track %>