config/routes.rb
MusicApp::Application.routes.draw do
  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end
  resources :tracks, except: [:index, :new] do
    resources :notes, only: :show
  end
  resources :notes, only: [:create, :destroy]
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id          :integer          not null, primary key
#  album_title :string(255)      not null
#  band_id     :integer          not null
#  album_type  :string(255)      not null
#  created_at  :datetime
#  updated_at  :datetime
#

class Album < ActiveRecord::Base

  validates :album_title, :band_id, :album_type, presence: true

  belongs_to(
    :band,
    :class_name => "Band",
    :foreign_key => :band_id,
    :primary_key => :id
  )

  has_many(
    :tracks,
    :dependent => :destroy,
    :class_name => "Track",
    :foreign_key => :album_id,
    :primary_key => :id
  )

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :require_current_user!

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(@album)
    else
      @band = Band.find(@album.band_id)
      render :new
    end
  end

  def new
    @album = Album.new
    @band = Band.find(params[:band_id])
    @album.band_id = @band.id
    render :new
  end

  def edit
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
    render :edit
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      @band = Band.find(@album.band_id)
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
    @album.destroy
    redirect_to band_url(@band.id)
  end


  private

  def album_params
    params.require(:album).permit(:album_title, :band_id, :album_type)
  end
end

app/views/albums/_album_form.html.erb
<% input_url = action == :new ? albums_url : album_url(album) %>
<% input_method = action == :new ? "post" : "patch" %>
<% button_text = action == :new ? "Create Album" : "Submit Changes" %>
<% bands = Band.all %>

<form action="<%= input_url %>" method="post">
  <input type="hidden" name="_method" value="<%= input_method %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="album_title">Album Title</label>
  <input id="album_title"
         type="text"
         name="album[album_title]"
         value="<%= album.album_title %>">

  <br>
  <label for="band_name">Band</label>
  <select id="band_name" name="album[band_id]">
    <% bands.each do |band| %>
      <option value="<%= band.id %>"
        <%= "selected" if band.id == album.band_id %> >
        <%= band.name %>
      </option>
    <% end %>
  </select>
  <br><br>
  Album Type
  <br>
  <label for="album_type_studio">Studio</label>
  <input id="album_type_studio" type="radio"
         name="album[album_type]" value="studio"
        <%= "checked" if album.album_type == "studio" %>  >

  <label for="album_type_live">Live</label>
  <input id="album_type_live" type="radio"
         name="album[album_type]" value="live"
        <%= "checked" if album.album_type == "live" %>  >
  <br>
  <button><%= button_text %></button>
</form>
<br>
<a href="<%= band_url(band) %>"><button><%= band.name %></button></a>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "album_form",
    album: @album,
    band: @band,
    action: :edit %>

app/views/albums/new.html.erb
<h1>Create Album</h1>
<%= render "album_form", album: @album, band: @band, action: :new %>

app/views/albums/show.html.erb
<% tracks = @album.tracks.all %>


<% band = Band.find(@album.band_id) %>

<h1><%= @album.album_title %></h1>

<br>
<% tracks.each do |track| %>
<a href="<%= track_url(track) %>">
<%= track.track_title %>
</a>
<br>
<% end %>
<br>

<a href="<%= new_album_track_url(@album) %>"><button>Add Track</button></a>
<br><br>

<a href="<%= edit_album_url(@album) %>"><button>Edit Album</button></a>
<br><br>

<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="delete">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <button>Delete This Album</button>
</form>
<br>
<a href="<%= band_url(band) %>"><button>All <%= band.name %> Albums</button></a>