config/routes.rb
MusicApp::Application.routes.draw do
  resource :session, only: [:create, :new, :destroy]
  resources :users, only: [:create, :new, :show]
  resources :bands do
    resources :albums, only: :new
  end
  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end
  resources :tracks, except: [:index, :new] do
    resources :notes, only: :show
  end
  resources :notes, only: [:create, :destroy]
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base

  validates :name, presence: { message: "Band name can't be blank" }


  has_many(
    :albums,
    :dependent => :destroy,
    :class_name => "Album",
    :foreign_key => :band_id,
    :primary_key => :id

  )
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :require_current_user!

  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      render :new
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def show
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/views/bands/_band_form.html.erb
<% input_url = action == :new ? bands_url : band_url(band) %>
<% input_method = action == :new ? "post" : "patch" %>
<% button_text = action == :new ? "Create Band" : "Submit Changes" %>

<form action="<%= input_url %>" method="post">
  <input type="hidden" name="_method" value="<%= input_method %>">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <label for="band_name">Band Name</label>
  <input id="band_name"
         type="text"
         name="band[name]"
         value="<%= band.name %>">

  <br>
  <br>
  <button><%= button_text %></button>
</form>
<br>
<a href="<%= bands_url %>"><button>All Bands</button></a>

app/views/bands/edit.html.erb
<h1>Edit a band</h1>

<%= render "band_form", band: @band, action: :edit %>

app/views/bands/index.html.erb
<h1>All bands</h1>
<br>
<% @bands.each do |band| %>
<a href="<%= band_url(band) %>">
<%= band.name %>
</a>
<br>
<% end %>

<br>
<a href="<%= new_band_url %>"><button>Add Band</button></a>

app/views/bands/new.html.erb
<h1>Create a band</h1>

<%= render "band_form", band: @band, action: :new %>

app/views/bands/show.html.erb
<% albums = @band.albums.all %>

<h1> <%= @band.name %> </h1>

<% albums.each do |album| %>
<a href="<%= album_url(album) %>">
<%= album.album_title %>
</a>
<br>
<% end %>

<br>
<a href="<%= new_band_album_url(@band) %>"><button>Add Album</button></a>

<br><br>
<a href="<%= edit_band_url(@band) %>"><button>Change Band Name</button></a>
<br><br>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="delete">

  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <button>Delete This Band</button>
</form>
<br>
<a href="<%= bands_url %>"><button>All Bands</button></a>